spring:
  application:
    name: gateway-service
  profiles:
    active: default
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - AuthFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - AuthFilter
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
          filters:
            - AuthFilter
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - AuthFilter


#      discovery:
#        locator:
#          enabled: true
#  cloud:
#    config:
#      uri: http://localhost:8888
#  redis:
#    port: 14239
#    host: redis-14239.c15.us-east-1-4.ec2.redns.redis-cloud.com
#    password: eS4ESjOuTJ6JrPcOemqi15I8JF3FvsMY
server:
  port: 8762
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

